    [project]
    name = "nanorecsys"
    version = "0.1.0"
    description = "Add your description here"
    readme = "README.md"
    requires-python = ">=3.14"
    dependencies = [
        "fastapi>=0.128.0",
        "mypy>=1.19.1",
        "numpy>=2.4.1",
        "pandas>=3.0.0",
        "pydantic-settings",
        "pytest>=9.0.2",
        "ruff>=0.14.13",
        "torch>=2.10.0",
        "uvicorn>=0.40.0",
    ]
