[project]
name = "nanoRecSys"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "ipykernel",
    "mypy",
    "numpy",
    "pandas",
    "pyarrow",
    "pydantic-settings",
    "pytest",
    "requests",
    "ruff",
    "torch",
    "tqdm",
    "uvicorn",
]
